# Generated by Django 5.2.7 on 2025-10-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fin de la période d'essai"),
        ),
    ]
